/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Category = IDL.Variant({
  'social' : IDL.Null,
  'arts' : IDL.Null,
  'academic' : IDL.Null,
  'sports' : IDL.Null,
});
export const ActivityInput = IDL.Record({
  'title' : IDL.Text,
  'date' : Time,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'location' : IDL.Text,
});
export const ActivityID = IDL.Nat;
export const Activity = IDL.Record({
  'id' : ActivityID,
  'organizer' : IDL.Principal,
  'title' : IDL.Text,
  'date' : Time,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'participantCount' : IDL.Nat,
  'category' : Category,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createActivity' : IDL.Func([ActivityInput], [ActivityID], []),
  'getActivityDetails' : IDL.Func([ActivityID], [IDL.Opt(Activity)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getParticipants' : IDL.Func(
      [ActivityID],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getUpcomingActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'getUserRegistrations' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ActivityID)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerForActivity' : IDL.Func([ActivityID], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Category = IDL.Variant({
    'social' : IDL.Null,
    'arts' : IDL.Null,
    'academic' : IDL.Null,
    'sports' : IDL.Null,
  });
  const ActivityInput = IDL.Record({
    'title' : IDL.Text,
    'date' : Time,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'location' : IDL.Text,
  });
  const ActivityID = IDL.Nat;
  const Activity = IDL.Record({
    'id' : ActivityID,
    'organizer' : IDL.Principal,
    'title' : IDL.Text,
    'date' : Time,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'participantCount' : IDL.Nat,
    'category' : Category,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createActivity' : IDL.Func([ActivityInput], [ActivityID], []),
    'getActivityDetails' : IDL.Func(
        [ActivityID],
        [IDL.Opt(Activity)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getParticipants' : IDL.Func(
        [ActivityID],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getUpcomingActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'getUserRegistrations' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ActivityID)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerForActivity' : IDL.Func([ActivityID], [], []),
  });
};

export const init = ({ IDL }) => { return []; };