/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : ActivityID,
  'organizer' : Principal,
  'title' : string,
  'date' : Time,
  'time' : string,
  'description' : string,
  'participantCount' : bigint,
  'category' : Category,
  'location' : string,
}
export type ActivityID = bigint;
export interface ActivityInput {
  'title' : string,
  'date' : Time,
  'time' : string,
  'description' : string,
  'category' : Category,
  'location' : string,
}
export type Category = { 'social' : null } |
  { 'arts' : null } |
  { 'academic' : null } |
  { 'sports' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createActivity' : ActorMethod<[ActivityInput], ActivityID>,
  'getActivityDetails' : ActorMethod<[ActivityID], [] | [Activity]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getParticipants' : ActorMethod<[ActivityID], Array<Principal>>,
  'getUpcomingActivities' : ActorMethod<[], Array<Activity>>,
  'getUserRegistrations' : ActorMethod<[Principal], Array<ActivityID>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerForActivity' : ActorMethod<[ActivityID], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];